Adding collision detection based on path.
TrentWDB/Mito-Physics pull request #1
Opened 2018-04-16 23:30 UTC by TravisForkner

tick percentage will eventually be stored in a queue along with the physics objects that collided.
detect collision return 0 - 1 or null on no collision.

2018-04-16 23:32 UTC, thechungster commented on MitoMathHelper.js
> +        }else{
redundant else

2018-04-17 02:05 UTC, kujukuju requested changes

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +
no extra line

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +    distanceBetweenTwoPoints(pointA, pointB){
static _distanceBetweenTwoPoints(pointA, pointB) {
include space between ) {

NOTE: you should probably return the squared hypot so you can avoid using the hypot function which calls sqrt, then only call sqrt if necessary or create another function that calls Math.sqrt(thisFunction(a, b));

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +    detectCollisionCirCir(circleA, circleB){
_detectCollisionCirleCirle(circleA, circleB) {

I wouldnt use abbreviations unless its really common

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let bounds = new MitoCircle();
you can just use a value and just do math on numbers

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        bounds.setRadius(circleA.getRadius() +  combineMagnitude);
no double space

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        if(!this.detectCollisionCirCir(bounds, circleB)){
if (!MitoMathHelper._detectCollisionCircleCircle(bounds, circleB)) {

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +
remove extra lines here

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +
at the end of the file do
MitoMathHelper.EPSILON = 0.000001;

when determining if things are perfectly equal use "Math.abs(value1 - EQUAL_VALUE) < MitoMathHelper.EPSILON" when applicable

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +    detectCollisionTime(circleA, velocityA, circleB, velocityB, interval){
static detectCollisionTime(circleA, velocityA, circleB, velocityB, interval) {

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let velocityIntA = this.multiplyPoint(velocityA, interval);
MitoMathHelper._multiplyPoint(velocityA, interval);

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let appliedVelocitiesToPositionA = this.addPoints(circleA.getPosition(), combineVelocity);
MitoMathHelper._addPoints(

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +            circleB.getPosition());
circleB.getPosition(),
);

If it lets you, it depends on the language level were using.

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let distance = this.distanceBetweenTwoPoints(closestCircle.getPosition(), circleB.getPosition());
MitoMathHelper._distanceBe...

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +            let backOff = Math.sqrt((radiusTotal*radiusTotal) - (distance*distance));
Math.sqrt((radiusTotal * radiusTotal) - (distance * distance));

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +            let backPoint = [backOff *( combineVelocity[0] / combineMagnitude) , backOff *( combineVelocity[1] / combineMagnitude)];
let backPoint = [backOff * (combineVelocity[0] / combineMagnitude), backOff * (combineVelocity[1] / combineMagnitude)];

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +            let closestPointWithinVelocity = this.addPoints(closestPoint , this.invertPoint(backPoint));
let closestPointWithinVelocity = this.addPoints(closestPoint, this.invertPoint(backPoint));

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +            console.assert(tickPercentage >= 0 && tickPercentage <= 1, "detectCollisionTime: value outside of range: " + tickPercentage );
I wouldnt use assert's/invariant's like this, and apparently console.assert is different in node vs browsers

if you want you can be like

if (something) {
    console.error('Blah');
}

or if you are really angry

if (something) {
    throw new Error('blah');
}

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +
no newline

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        return  radiusTotal >= distance;
you can avoid using sqrt here, one of probably many places I didnt see.

no double space.

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let A_to_P = [singlePoint[0] - linePointA[0], singlePoint[1] - linePointA[1]] ;
aToP, no space before ";"

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let A_to_B = [linePointB[0] - linePointA[0], linePointB[1] - linePointA[1]];
same

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        if(atb2 === 0){return linePointA;}
if (atb2 === 0) {
    return linePointA;
}

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        let atp_dot_atb = (A_to_P[0]*A_to_B[0]) + (A_to_P[1] * A_to_B[1]);
no underscores, spaces before and after *, so its consistent

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        return [pointA[0] + pointB[0] , pointA[1] + pointB[1]];
no space before ","

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        return [point[0] * -1 , point[1] * -1];
you can do it this way, "* -1", or you can do "-point[0]"

either way is fine, I like -point[0], but you could argue that * -1 is more explicit

no space before comma

2018-04-17 02:05 UTC, TrentWDB commented on MitoMathHelper.js
> +        return [point[0] * value , point[1] * value];
no space before comma, private function, static function, etc

2018-04-17 04:32 UTC, kujukuju approved these changes
make changes before merging

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +        let velocityIntA = this._multiplyPoint(velocityA, interval);
dont do this. since its static

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +        if (!this._detectCollision(circleA.getPosition(),
put the condition into a variable before the if statement since its so long

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +        let closestPoint = this._getClosestPoint(circleA.getPosition(),
move circleA.getPosition to the next line

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +            pointA[1] - pointB[1]);
pointA[1] - pointB[1],
);

you don't need to do sqrt here, find all places where you don't need to do sqrt

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +        let atpDotAtb = (aToP[0] * aToB[0]) + (aToP[1] * aToB[1]);
let aToPDotAToB = ...
more descriptive naming

2018-04-17 04:32 UTC, TrentWDB commented on MitoMathHelper.js
> +        return [linePointA[0] + (aToB[0] * normalizedDistance), linePointA[1] + (aToB[1] * normalizedDistance)]
you dont need () around the multiplication here but it doesnt really matter either way

2018-04-17 05:08 UTC, merged